name: DevTools
main: DevTools\DevTools
version: 1.11.1
api: [2.0.0, 3.0.0-ALPHA3]
load: STARTUP
author: PocketMine Team
description: Helps develop and distribute PocketMine-MP plugins
website: https://github.com/PocketMine/DevTools
permissions:
 devtools:
  default: op
  description: "Allows using all the DevTools things"
  children:
   devtools.command:
    default: op
    description: "Allows using all the DevTools commands"
    children:
     devtools.command.makeplugin:
      default: op
      description: "Allows the creation of Phar plugins"
     devtools.command.extractplugin:
      default: op
      description: "Allows the extraction of Phar plugins"
     devtools.command.makeserver:
      default: op
      description: "Allows the creation of a PocketMine-MP Phar"
     devtools.command.checkperm:
      default: true
      description: "Allows checking a permission value"
      children:
       devtools.command.checkperm.other:
        default: op
        description: "Allows checking others permission value"
