name: DevTools
main: DevTools\DevTools
src-namespace-prefix: DevTools
version: 1.17.1+dev
api: [5.0.0]
load: STARTUP
author: PocketMine Team
description: Helps develop and distribute PocketMine-MP plugins
website: https://github.com/PocketMine/DevTools
commands:
 makeplugin:
  description: Creates a Phar plugin from one in source code form
  usage: "/makeplugin <pluginName>"
  permission: devtools.command.makeplugin
 checkperm:
  description: Checks a permission value for the current sender, or a player
  usage: "/checkperm <node> [playerName]"
  permission: "devtools.command.checkperm;devtools.command.checkperm.other"
 listperms:
  description: Lists all the permission nodes set on the executor, or a player
  usage: "/listperms [playerName]"
  permission: "devtools.command.listperms.self;devtools.command.listperms.other"
 handlers:
  description: Lists all event handlers currently associated with an event
  usage: "/handlers <event>"
  permission: devtools.command.handlers
 handlersbyplugin:
  description: Lists all event handlers registered by a given plugin
  usage: "/handlersbyplugin <pluginName>"
  permission: devtools.command.handlersbyplugin
permissions:
 devtools.command.makeplugin:
  default: op
  description: "Allows the creation of Phar plugins"
 devtools.command.extractplugin:
  default: op
  description: "Allows the extraction of Phar plugins"
 devtools.command.checkperm:
  default: true
  description: "Allows checking a permission value"
 devtools.command.checkperm.other:
  default: op
  description: "Allows checking others permission value"
 devtools.command.genplugin:
  default: op
  description: "Allows the user to generate skeleton files for a plugin"
 devtools.command.listperms.self:
  default: op
  description: "Allows the user to list their own permissions"
 devtools.command.listperms.other:
  default: op
  description: "Allows the user to list another player's permissions"
 devtools.command.handlers:
  default: op
  description: "Allows the user to list handlers associated with an event"
 devtools.command.handlersbyplugin:
  default: op
  description: "Allows the user to list event handlers registered by a given plugin"
